// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbWRiKzXMXurSVZnkxWROv-_EXKhpiAJk',
    appId: '1:240056675197:web:06e34233bd07f8ac3c7a14',
    messagingSenderId: '240056675197',
    projectId: 'flutter-practice-fcm',
    authDomain: 'flutter-practice-fcm.firebaseapp.com',
    storageBucket: 'flutter-practice-fcm.appspot.com',
    measurementId: 'G-GSM8PF9H2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsLgOMuKWzhrEKui9uM3KnlZL8DTFp7x8',
    appId: '1:240056675197:android:d486be7e253df2233c7a14',
    messagingSenderId: '240056675197',
    projectId: 'flutter-practice-fcm',
    storageBucket: 'flutter-practice-fcm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU83a2D_zjH43zMlEvso6tBKepTHch82s',
    appId: '1:240056675197:ios:42fa561c3f1551953c7a14',
    messagingSenderId: '240056675197',
    projectId: 'flutter-practice-fcm',
    storageBucket: 'flutter-practice-fcm.appspot.com',
    iosClientId: '240056675197-982630e992s7mah1r0plvsqbeo3gb3dr.apps.googleusercontent.com',
    iosBundleId: 'com.example.cleanArquiBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU83a2D_zjH43zMlEvso6tBKepTHch82s',
    appId: '1:240056675197:ios:42fa561c3f1551953c7a14',
    messagingSenderId: '240056675197',
    projectId: 'flutter-practice-fcm',
    storageBucket: 'flutter-practice-fcm.appspot.com',
    iosClientId: '240056675197-982630e992s7mah1r0plvsqbeo3gb3dr.apps.googleusercontent.com',
    iosBundleId: 'com.example.cleanArquiBase',
  );
}
